/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...error]': RouteRecordInfo<
      '/[...error]',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    '/account-settings': RouteRecordInfo<
      '/account-settings',
      '/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-basic': RouteRecordInfo<
      '/card-basic',
      '/card-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cards': RouteRecordInfo<
      '/cards',
      '/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/form-layouts': RouteRecordInfo<
      '/form-layouts',
      '/form-layouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/icons': RouteRecordInfo<
      '/icons',
      '/icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tables': RouteRecordInfo<
      '/tables',
      '/tables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/typography': RouteRecordInfo<
      '/typography',
      '/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...error].vue': {
      routes:
        | '/[...error]'
      views:
        | never
    }
    'src/pages/account-settings.vue': {
      routes:
        | '/account-settings'
      views:
        | never
    }
    'src/pages/card-basic.vue': {
      routes:
        | '/card-basic'
      views:
        | never
    }
    'src/pages/cards.vue': {
      routes:
        | '/cards'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/form-layouts.vue': {
      routes:
        | '/form-layouts'
      views:
        | never
    }
    'src/pages/icons.vue': {
      routes:
        | '/icons'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/tables.vue': {
      routes:
        | '/tables'
      views:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
    }
    'src/pages/typography.vue': {
      routes:
        | '/typography'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
